// src/views/Matematica/Adicao.vue
<template>
  <div class="operacao-container">
    <div class="d-flex justify-evenly">
      <Voltar />

      <div>
        <label for="nivel">Selecionar nível:</label>
          <select id="nivel" v-model="nivelSelecionado" @change="gerarPergunta" class=" ml-1 pl-2 bg-white rounded">
          <option v-for="nivel in niveis" :key="nivel" :value="nivel">
            Até {{ nivel }}
          </option>
          </select>
      </div>

      <div class="ml-8">
        Recorde: {{ recorde }}
      </div>
      </div>

    <div class="display-placar">
      Pontos:
      <div class="placar">{{ placar }}</div>
    </div>

    <div class="display-pergunta">
      {{ num1 }} + {{ num2 }} =
      <span>{{ resposta !== -1 ? resposta : '?' }}</span>
    </div>

    <div class="botoes">
      <div class="botoes-resposta">
        <button
          v-for="i in 10"
          :key="i - 1"
          class="btn-resposta"
          @click="escreverResposta(i - 1)">
          {{ i - 1 }}
        </button>
      </div>
    
      <div class="d-flex">
        <button class="btn-resposta btn-largo btn-apagar  px-6" @click="apagarResposta()">« <small class="ml-2">APAGAR</small></button>
        <button class="btn-resposta btn-largo  px-6" @click="verificarResposta()">= <small class="ml-2">RESPOSTA</small> </button>
      </div>
    </div>
    <Modal />
  </div>
</template>

<script setup>
import { ref, onMounted, watch } from 'vue'
import Voltar from '@/components/Voltar.vue'
import Modal, { abrirModal } from '@/components/Modal.vue'

const pagina = 'adicao'

const placar = ref(0)
const recorde = ref(0)
const resposta = ref(-1)
const num1 = ref(0)
const num2 = ref(0)

const niveis = [10, 20, 30, 50, 100]

// inicia com valor salvo ou 10
const nivelSelecionado = ref(10)

function carregarConfiguracoesSalvas() {
  const salvoNivel = localStorage.getItem(`nivel-${pagina}`)
  const salvoRecorde = localStorage.getItem(`recorde-${pagina}`)

  if (salvoNivel && !isNaN(parseInt(salvoNivel))) {
    nivelSelecionado.value = parseInt(salvoNivel)
  }

  if (salvoRecorde && !isNaN(parseInt(salvoRecorde))) {
    recorde.value = parseInt(salvoRecorde)
  }
}

// observa alterações no nível e salva
watch(nivelSelecionado, (val) => {
  localStorage.setItem(`nivel-${pagina}`, val.toString())
  gerarPergunta()
})

function gerarPergunta() {
  const limite = nivelSelecionado.value
  let n1 = Math.floor(Math.random() * limite)
  let n2 = Math.floor(Math.random() * limite)

  while (n1 + n2 > limite) {
    n1 = Math.floor(Math.random() * limite)
    n2 = Math.floor(Math.random() * limite)
  }

  num1.value = n1
  num2.value = n2
  resposta.value = -1
}

function escreverResposta(num) {
  if (resposta.value === -1) {
    resposta.value = num
  } else {
    const nova = resposta.value.toString() + num.toString()
    if (nova.length <= 3) {
      resposta.value = parseInt(nova)
    }
  }
}

function apagarResposta() {
  if (resposta.value >= 10) {
    resposta.value = parseInt(resposta.value.toString().slice(0, -1))
  } else {
    resposta.value = -1
  }
}

function verificarResposta() {
  const correta = num1.value + num2.value
  if (resposta.value === correta) {
    placar.value++
    if (placar.value > recorde.value) {
      recorde.value = placar.value
      localStorage.setItem(`recorde-${pagina}`, recorde.value.toString())
    }
    abrirModal('Parabéns, você acertou!', 'green')
  } else {
    abrirModal('Infelizmente, você errou', 'red')
  }
  gerarPergunta()
}

onMounted(() => {
  carregarConfiguracoesSalvas()
  gerarPergunta()
})
</script>

// src/games/matematica/adicao/Adicao.tsx
import React, { useState, useEffect } from "react";
import Voltar from "../../../components/Voltar";
import "./Adicao.css";

const Adicao = () => {
  const [num1, setNum1] = useState<number>(0);
  const [num2, setNum2] = useState<number>(0);
  const [placar, setPlacar] = useState<number>(0);
  const [resposta, setResposta] = useState<number>(-1);
  const [conteudoModal, setConteudoModal] = useState<string>(" VAZIO ");

  //inicia gerando uma questão
  useEffect(() => {
    gerarPergunta();
  }, []);

  // gerar questão aleatoria
  const gerarPergunta = () => {
    const novoNum1 = Math.floor(Math.random() * 10);
    let novoNum2 = Math.floor(Math.random() * 10);

    // while (novoNum1 === novoNum2) {
    //   novoNum2 = Math.floor(Math.random() * 10);
    // }

    setNum1(novoNum1);
    setNum2(novoNum2);
  };

  const escreverResposta = (num: number) => {
    console.log("num: ", num);
    console.log("resposta: ", resposta);

    if (resposta === -1) {
      setResposta(num);
      return;
    } else setResposta(parseInt(resposta.toString() + num.toString()));

    // subistitui caso ja tenha dois digitos
    if (resposta.toString().length === 2) {
      setResposta(-1);
    }
  };

  // apagar estilo backspace com o slice(0,-1)
  const apagarResposta = () => {
    resposta >= 10 ? setResposta(parseInt(resposta.toString().slice(0, -1))) : setResposta(-1);
  }

  const verificarResposta = (resposta: number) => {

    if (resposta === num1 + num2) {
      setPlacar(placar + 1);
      abrirModal("Parabéns, você acertou!", "green");
      setResposta(-1);
      gerarPergunta();
      return
    }
    abrirModal("Infelizmente, você Errou", "red");
    setResposta(-1);
    gerarPergunta();

  };

  const abrirModal = (msg: string = "VAZIO", color: string = "black") => {

    let myModal = document.getElementById("myModal")
    let modalStatus = myModal!.style.display;
    setConteudoModal(msg);
    myModal?.style.setProperty("background-color", color);

    if (modalStatus === "block") {
      myModal!.style.display = "none";
    } else {
      myModal!.style.display = "block";
    }
  };



  return (
    <div className="operacao-container">
      <Voltar />
      <div className="display-placar">
        Pontos:
        <div className="placar"> {placar}</div>
      </div>
      <div className="display-pergunta">
        {num1} + {num2} = {resposta !== -1 ? <span>{resposta}</span> : <span>?</span>}
      </div>
      <div className="botoes-resposta">
        {Array.from({ length: 10 }, (_, i) => (
          <button className="btn-resposta" key={i} onClick={() => escreverResposta(i)}>
            {i}
          </button>
        ))}
        <button className="btn-resposta btn-apagar" onClick={() => apagarResposta()}> « </button>
        <button className="btn-resposta" onClick={() => verificarResposta(resposta)}> = </button>
      </div>

      <div className="modal" id="myModal">
        <div className="modal-content" onClick={() => abrirModal()}>
          {/* <span className="close" onClick={() => abrirModal()}>&times;</span> */}
          {/* <p >{resposta === num1 + num2 ? "Acertou!" : "Errou!"}</p> */}
          <p>{conteudoModal}</p>
        </div>
      </div>
    </div>
  );
};

export default Adicao;
