// src/components/Modal.tsx
import React, { useState } from "react";

interface modalProps {
  colorModal?: string;
  conteudoModal?: string;
}

export const Modal: React.FC<modalProps> = ({ colorModal = "green", conteudoModal = "" }) => {
  const urlDinoImg = colorModal === "green" ? "/assets/dino-feliz.png" : "/assets/dino-triste.png";

  return (
    <>
      <div className="modal" id="myModal">
        <div className="modal-content" onClick={() => abrirModal()}>
          <p id="modalText">{conteudoModal}</p>
          <img id="dinoImg" width="150px" src={urlDinoImg} alt="" />
        </div>
      </div>
    </>
  );
};

export const abrirModal = (msg: string = "VAZIO", color: string = "black") => {
  let myModal = document.getElementById("myModal");
  let modalStatus = myModal!.style.display;

   //mudar imagem dino
   const urlimgDino = color === "green" ? "/assets/dino-feliz.png" : "/assets/dino-triste.png";
   document.getElementById("dinoImg")!.setAttribute("src", urlimgDino);
 
  // mudar cor do fundo
  myModal?.style.setProperty("background-color", color);

 
  //mudar texto no modal
  document.getElementById("modalText")!.innerHTML = msg;

  // mudar display do modal
  myModal!.style.display = modalStatus === "block" ? "none" : "block";
};

// src/components/Modal.vue
<template>
  <div class="modal" id="myModal">
    <div class="modal-content" @click="fecharModal">
      <p id="modalText" class="mb-4">{{ conteudoModal }}</p>
      <img id="dinoImg" :src="urlDinoImg" alt="" width="150px" />
      <h6 class="mt-4">Clique para Continuar</h6>
    </div>
  </div>
</template>

<script setup>
import { computed, defineProps } from 'vue'

const props = defineProps({
  colorModal: { type: String, default: 'green' },
  conteudoModal: { type: String, default: '' }
})

const urlDinoImg = computed(() =>
  props.colorModal === 'green' ? '/assets/dino-feliz.png' : '/assets/dino-triste.png'
)

const fecharModal = () => abrirModal() // reusa a função global abaixo
</script>

<script>
// função global para abrir o modal programaticamente
export function abrirModal(msg = 'VAZIO', color = 'black') {
  const myModal = document.getElementById('myModal')
  const modalStatus = myModal?.style.display

  const img = document.getElementById('dinoImg')
  if (img) img.setAttribute('src', color === 'green' ? '/assets/dino-feliz.png' : '/assets/dino-triste.png')

  if (myModal) {
    myModal.style.backgroundColor = color
    document.getElementById('modalText').innerHTML = msg
    myModal.style.display = modalStatus === 'block' ? 'none' : 'block'
  }
}
</script>
